---
title: C26111 | Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
caps.latest.revision: 10
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: d6fa9c7ac56a96e7413e3b508e4ab581e5c3eef5
ms.sourcegitcommit: 9ceaf69568d61023868ced59108ae4dd46f720ab
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 10/12/2018
ms.locfileid: "49227814"
---
# <a name="c26111"></a>C26111
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

avviso C26111: il chiamante non riesce a rilasciare il blocco \<lock > prima di chiamare funzioni \<func >.  
  
 L'annotazione `_Requires_lock_not_held_` impone una precondizione che il conteggio dei blocchi per il blocco specificato non può essere maggiore di zero quando viene chiamata la funzione. Avviso C26111 viene generato quando una funzione non riesce a rilasciare il blocco prima di chiamare un'altra funzione.  
  
## <a name="example"></a>Esempio  
 Nell'esempio seguente genera l'avviso C26111 perché il `_Requires_lock_not_held_` precondizione viene violata dalla chiamata al metodo `DoNotLock` all'interno della sezione bloccata.  
  
```  
  
typedef struct _DATA   
{  
    CRITICAL_SECTION cs;  
    int d;  
} DATA;  
  
_Requires_lock_not_held_(p->cs)   
  
void DoNotLock(DATA* p)  
{  
    EnterCriticalSection(&p->cs);   
    p->d = 0;  
    LeaveCriticalSection(&p->cs);  
}  
  
void LockedFunction(DATA* p)   
{   
    EnterCriticalSection(&p->cs);   
    DoNotLock(p); // Warning C26111  
    LeaveCriticalSection(&p->cs);  
}  
  
```



